# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161224185311 on 2017-01-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scripture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=255)),
                ('chapter', models.IntegerField()),
                ('verses', models.IntegerField()),
                ('content', models.TextField()),
                ('pid_list', models.ManyToManyField(to='main.Prayer_point')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='sid_list',
            field=models.ManyToManyField(to='main.Scripture'),
        ),
    ]
