# Generated by Django 3.0.1 on 2019-12-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=64)),
                ('bible_ref', models.CharField(default='No Bible ref', max_length=64)),
                ('scripture', models.TextField(default='No scripture', max_length=2048)),
                ('content', models.TextField(max_length=2048)),
                ('category', models.TextField(max_length=128)),
            ],
        ),
    ]
