# Generated by Django 3.0.1 on 2020-01-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerpoint',
            name='title',
        ),
    ]
