# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_prayer_point_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer_point',
            name='book',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prayer_point',
            name='chapter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prayer_point',
            name='verse',
            field=models.IntegerField(default=1),
        ),
    ]
