# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170624_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayer_point',
            old_name='description',
            new_name='title',
        ),
    ]
