# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170624_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_of_chapters',
            field=models.IntegerField(default=1),
        ),
    ]
