# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_book_no_of_chapters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prayer_point',
            new_name='PrayerPoint',
        ),
    ]
