# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_category_sid_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default=b'no_desc', max_length=512),
        ),
    ]
